services:
  frontend:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev