services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_php
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    working_dir: /var/www/html
    environment:
      - PHP_MEMORY_LIMIT=256M
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  database:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: app
      MYSQL_USER: app
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - database

volumes:
  db_data:
    name: laravel_db_data
